### ISSUE TITLE
Resolve issues with database access

### ISSUE THREAD

**Issue by iangow** [mccgr/cpr#2]
@bhaskarv9 

You say you are having trouble accessing the database. Please paste code you are using that is not working as comments here. (You can use [GitHub-flavoured Markdown](https://guides.github.com/features/mastering-markdown/) here, just like in other parts of GitHub.)

**Comment by iangow** [comment]
@bhaskarv9 Is this all solved now?

**Comment by bhaskarv9** [comment]
No it is still showing up as false

**Comment by bhaskarv9** [comment]
dbExistsTable(con,c("sirca.directors"))
[1] FALSE

I am still getting the above response

**Comment by iangow** [comment]
But I think we resolved that [here](https://github.com/iangow/pg_functions/issues/1). (I'm not sure why a new issue was created there.)
